mswp/urls.py
from django.contrib import admin
from django.urls import path, include

from mswp import views

urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
    path('record/', include('record.urls', namespace='record')),
]

record/urls.py
from django.urls import path
from record import views

app_name = 'record'

urlpatterns = [
    path('', views.record_list, name='record_list'),
    path('record_list/<int:difficulty>', views.record_list, name='record_list'),
    path('user_record/', views.user_record, name='user_record'),
    path('record_insert/', views.record_insert, name='record_insert')

]

record/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.

# 保存所有记录
class Record(models.Model):
    DIFFICULTY_CHOICES = (
        (1, 'Beginner'), (2, 'Intermediate'), (3, 'Expert'), (4, 'Custom')
    )
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    difficulty = models.IntegerField(choices=DIFFICULTY_CHOICES, default=1)
    finish_time = models.IntegerField(default=-1)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<Record: player: %s, time: %d>' % (self.player, self.finish_time)

    class Meta:
        db_table = 'record'


# 保存用户各难度的最佳记录
class BestRecord(models.Model):
    DIFFICULTY_CHOICES = (
        (1, 'Beginner'), (2, 'Intermediate'), (3, 'Expert'), (4, 'Custom')
    )
    player = models.ForeignKey(User, on_delete=models.CASCADE)
    difficulty = models.IntegerField(choices=DIFFICULTY_CHOICES, default=1)
    finish_time = models.IntegerField(default=-1)
    create_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '<BestRecord: Player: %s, Difficulty: %d, Finish Time: %d>' % (self.player, self.difficulty, self.finish_time)

    class Meta:
        db_table = 'best_record'

mswp/views.py
from django.shortcuts import render, redirect
from django.contrib import auth
from django.contrib.auth.models import User
from django.urls import reverse
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    ))

    def clean(self):
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        user = auth.authenticate(username=username, password=password)
        if user is None:
            raise forms.ValidationError('Invalid username or password')
        else:
            self.cleaned_data['user'] = user
        return self.cleaned_data


class RegForm(forms.Form):
    username = forms.CharField(max_length=16, min_length=6, widget=forms.TextInput(
        attrs={'class': 'form-control', 'placeholder': 'Username'}
    ))
    email = forms.EmailField(max_length=30, widget=forms.EmailInput(
        attrs={'class': 'form-control', 'placeholder': 'Email'}
    ))
    password = forms.CharField(max_length=24, min_length=8, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password'}
    ))
    confirm_password = forms.CharField(max_length=24, min_length=8, widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Confirm Password'}
    ))

    def clean(self):
        username = self.cleaned_data['username']
        if User.objects.filter(username=username).exists():
            raise forms.ValidationError('Username already exists')

        email = self.cleaned_data['email']
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email has been registered')

        password = self.cleaned_data['password']
        confirm_password = self.cleaned_data['confirm_password']
        if password != confirm_password:
            raise forms.ValidationError('Passwords do not match')

        return self.cleaned_data


def index(request):
    if request.user.is_authenticated:
        return render(request, "index.html")
    else:
        return redirect('login')


def login(request):
    if request.user.is_authenticated:
        return redirect('index')
    form = LoginForm(request.POST or None)
    if form.is_valid():
        user = form.cleaned_data['user']
        auth.login(request, user)
        return redirect(request.GET.get('from', reverse('index')))

    data = {'form': form}
    return render(request, 'login.html', data)


def logout(request):
    auth.logout(request)
    return redirect((request.GET.get('from', reversed('index'))))


def register(request):
    if request.user.is_authenticated:
        return redirect('index')
    form = RegForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data['username']
        email = form.cleaned_data['email']
        password = form.cleaned_data['password']
        User.objects.create_user(username, email, password)

        user = auth.authenticate(username=username, password=password)
        auth.login(request, user)
        return redirect(request.GET.get('from', reverse('index')))

    data = {'form': form}
    return render(request, 'register.html', data)

record/views.py
from django.contrib.auth.models import User
from django.db.models import Q
from django.shortcuts import render, redirect, get_object_or_404

from record.models import Record, BestRecord


# Create your views here.

def record_list(request):
    context = {}
    difficulty = int(request.GET.get('difficulty', default=1))
    objs = BestRecord.objects.filter(difficulty=difficulty).order_by('finish_time')
    context['object_list'] = objs

    if difficulty == 1:
        context['difficulty'] = 'Beginner'
    elif difficulty == 2:
        context['difficulty'] = 'Intermediate'
    elif difficulty == 3:
        context['difficulty'] = 'Expert'

    return render(request, 'record_list.html', context)


def user_record(request):
    data = {}
    player_id = request.GET.get('player_id')
    difficulty = request.GET.get('difficulty')
    player = get_object_or_404(User, pk=player_id)

    if player is not None:
        objs = Record.objects.filter(Q(player_id=player_id) & Q(difficulty=difficulty)).order_by('finish_time')
        data['object_list'] = objs.order_by('finish_time')
        data['player'] = player
        return render(request, 'user_record.html', data)
    else:
        return redirect('index')


def record_insert(request):
    player_id = request.POST.get('player_id')
    difficulty = request.POST.get('difficulty')
    finish_time = request.POST.get('finish_time')

    player = User.objects.get(pk=player_id)
    record = Record()
    record.player = player
    record.difficulty = difficulty
    record.finish_time = finish_time
    record.save()

    try:
        best_record = BestRecord.objects.get(player_id=player_id, difficulty=difficulty)
    except BestRecord.DoesNotExist:
        best_record = None

    if best_record is None:
        best_record = BestRecord()
        best_record.player = player
        best_record.difficulty = difficulty
        best_record.finish_time = 999999999999

    best_record.finish_time = min(best_record.finish_time, int(finish_time))
    best_record.save()

    return redirect('index')

record/templates/record_list.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="jumbotron" style="padding: 25px; background: #fff; margin: 0">
                  <h3 class="display-6">Difficulty:&nbsp;{{ difficulty }}</h3>
                    <hr class="my-3">
                    <a href="{% url 'record:record_list'%}?difficulty=1" class="badge badge-success">&nbsp;Beginner&nbsp;</a>
                    <a href="{% url 'record:record_list'%}?difficulty=2" class="badge badge-primary">&nbsp;Intermediate&nbsp;</a>
                    <a href="{% url 'record:record_list'%}?difficulty=3" class="badge badge-danger">&nbsp;Expert&nbsp;</a>
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">ID</th>
                        <th scope="col">Player</th>
                        <th scope="col">Time</th>
                        <th scope="col">Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for record in object_list %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <td>{{ record.player_id }}</td>
                            <td>
                                <a href="{% url 'record:user_record' %}?player_id={{ record.player_id }}&difficulty=1">{{ record.player }}</a>
                            </td>
                            <td>{{ record.finish_time }}&nbsp;s</td>
                            <td>{{ record.create_time }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>

{% endblock %}

record/templates/user_record.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="card">
            <div class="card-body">
                <div class="jumbotron" style="padding: 25px; background: #fff; margin: 0">
                  <h3 class="display-6">Player:&nbsp;{{ player.username }}</h3>
                    <hr class="my-3">
                    <a href="{% url 'record:user_record' %}?player_id={{ player.pk }}&difficulty=1" class="badge badge-success">&nbsp;Beginner&nbsp;</a>
                    <a href="{% url 'record:user_record' %}?player_id={{ player.pk }}&difficulty=2" class="badge badge-primary">&nbsp;Intermediate&nbsp;</a>
                    <a href="{% url 'record:user_record' %}?player_id={{ player.pk }}&difficulty=3" class="badge badge-danger">&nbsp;Expert&nbsp;</a>
                </div>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Difficulty</th>
                        <th scope="col">Time</th>
                        <th scope="col">Date</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for record in object_list %}
                        <tr>
                            <td scope="row">{{ forloop.counter }}</td>
                            <td>{{ record.get_difficulty_display }}</td>
                            <td>{{ record.finish_time }}&nbsp;s</td>
                            <td>{{ record.create_time }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
                <br>
            </div>
        </div>
    </div>

{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel="stylesheet/less" type="text/css" href="{% static 'css/styles.less' %}" />

    {% block head %}

    {% endblock %}

</head>
<body>

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
            <a class="navbar-brand" href="{% url 'index' %}">LOKKA</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">Minesweeper</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'record:record_list'%}?difficulty=1">Rank</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Community</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Support</a>
                </li>
            </ul>

            {% if user.is_authenticated %}
                <a class="nav-link navbar-user" href="/">Hello, {{ user.username }}</a>
                <a class="nav-link navbar-user" href="{% url 'logout' %}?from={{ request.get_full_path }}">Logout</a>
            {% else %}
                <a class="nav-link navbar-user" href="{% url 'login' %}?from={{ request.get_full_path }}">Login</a>
                <a class="nav-link navbar-user" href="{% url 'register' %}?from={{ request.get_full_path }}">Register</a>
            {% endif %}

        </div>
    </div>
</nav>


<div class="container">
    <div class="row">
        <div class="col-md-12">

        </div>
    </div>

</div>



{% block content %}

{% endblock %}

<footer class="footer">
    <div class="container">
        <div class="col-lg-12 col-md-10" style="margin-bottom:10px;">
            <span class="footer-brand">LOKKA</span>
            <span class="footer-text">&copy;&nbsp;Zhang Jian</span>
        </div>
        <div class="col-lg-12 col-md-10">
            <span class="footer-text">541713460143, Software Engineering 17-01</span>
        </div>
        <div class="col-lg-12 col-md-10">
            <span class="footer-text">ZZULI, Kexue Ave. No.136, Zhengzhou(450000), Henan, China</span>
        </div>
    </div>
</footer>

{#    <script src="https://cdnjs.cloudflare.com/ajax/libs/less.js/3.11.1/less.min.js" ></script>#}
    <script src="{% static 'js/less.min.js' %}"  ></script>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load static %}

{% block head %}
  <script type="text/javascript" src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
  <script type="text/javascript" src="{% static 'js/minesweeper.js' %}"></script>
{% endblock %}

{% block content %}

  <div class="container">
    <div class="card rounded ">
      <div class="card-body">
        <div class="jumbotron" style="padding: 25px; background: #fff; margin: 0">
          <h3 class="display-6">Select the difficulty level and start your game</h3>
          <hr class="my-3">
{#          10  40   99#}
          <a href="javascript:" onclick="init(10,10,10); setDifficulty(1);" class="badge badge-success">&nbsp;Beginner&nbsp;</a>
          <a href="javascript:" onclick="init(16,16,40); setDifficulty(2)" class="badge badge-primary">&nbsp;Intermediate&nbsp;</a>
          <a href="javascript:" onclick="init(30,16,99); setDifficulty(3)" class="badge badge-danger">&nbsp;Expert&nbsp;</a>
        </div>

        <img id="mswp-banner" src="https://cdn.jsdelivr.net/gh/kainzhang/kz-img/blog/common/daniel-cheung-cPF2nlWcMY4-unsplash.jpg" class="img-fluid" alt="Responsive image">

          <div id="mswp-submenu" hidden>
            <span>Time</span>&nbsp;<span id="time" class="badge badge-light">0</span>
            <span style="margin-left: 100px">Mine</span>&nbsp;<span id="lastnum" class="badge badge-light"></span>
            <br>
          </div>
          <div id="mswp-container">
          </div>

          <!-- Modal -->
          <div class="modal fade" id="staticBackdrop" data-backdrop="static" data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="staticBackdropLabel">Your Win! Submit your record!</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <form id="record-form" action="{% url 'record:record_insert' %}" method="post">
                  {% csrf_token %}

                  <div class="modal-body">
                    <div class="form-group">
                      <label for="player">Player ID</label>
                      <input type="text" class="form-control" id="player" name="player_id" value="{{ user.id }}" readonly>
                    </div>

                    <div class="form-group">
                      <label for="difficulty">Difficulty</label>
                      <select class="form-control" id="difficulty" name="difficulty" disabled>
                        <option value="1">Beginner</option>
                        <option value="2">Intermediate</option>
                        <option value="3">Expert</option>
                        <option value="4">Custom</option>
                      </select>
                    </div>

                    <div class="form-group">
                      <label for="finish_time">Finish Time</label>
                      <input class="form-control" type="text" id="finish_time" name="finish_time" readonly>
                    </div>
                  </div>

                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-primary" onclick="$('#difficulty').removeAttr('disabled');">Submit</button>
                  </div>

                </form>
              </div>
            </div>
          </div>
          <!-- Modal End -->
      </div>
    </div>
  </div>

  <script type="text/javascript">
    Window.onload = function(){
      init(10,10,1);
      setDifficulty(1);
    }
  </script>


{% endblock %}

templates/login.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
        <div class="col-xl-5">
            <div class="card rounded ">
                <div class="card-body">
                    <br>
                    <h2>Please sign in.</h2>
                    <br>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>
                        {% else %}
                            <br><br>
                        {% endif %}
                        <input type="submit" class="btn btn-primary" value="Sign in">
                        &nbsp;<a href="{% url 'register' %}">No account? Create one now!</a>
                        <br><br>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>

{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block content %}

    <div class="container">
        <div class="row">
        <div class="col-xl-5">
            <div class="card rounded ">
                <div class="card-body">
                    <br>
                    <h2>Create your LOKKA ID.</h2>
                    <br>
                    <form method="post">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }}</label>
                                {{ field }}
                            </div>
                        {% endfor %}
                        {% if form.non_field_errors %}
                            <div class="alert alert-danger" role="alert">{{ form.non_field_errors }}</div>
                        {% else %}
                            <br><br>
                        {% endif %}
                        <input type="submit" class="btn btn-primary" value="Sign up">
                        &nbsp;<a href="{% url 'login' %}">Already have an account? Login now!</a>
                        <br><br>
                    </form>
                </div>
            </div>
        </div>
        </div>
    </div>

{% endblock %}